
package misegundoprograma;

import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrarFactura extends javax.swing.JFrame {
MiSegundoPrograma cc=new MiSegundoPrograma();
Connection cn=cc.conexion();
DefaultTableModel TablaFacturas;
String RegistroFactura[]=new String[8];
    public static String codproveedor;
    public static String OrdenComp;
    public static String Aux_General_Proveedor;
    public static String nrofactura;
    private double sumaBDOrdenCompra;
    private double sumaRegistroFactura;
    
    public RegistrarFactura() {
        initComponents();
        TablaFacturas=new DefaultTableModel();
        TablaFacturas.addColumn("Factura");
        TablaFacturas.addColumn("Nº Compra");
        TablaFacturas.addColumn("Cod Prod");
        TablaFacturas.addColumn("Fecha");
        TablaFacturas.addColumn("Descripción");
        TablaFacturas.addColumn("Cant/Unid");
        TablaFacturas.addColumn("Precio");
        TablaFacturas.addColumn("Monto");
        txtFechaSistema.setText(FechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuitProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCuilProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTFLProveedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtablaRegistrarFactura = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtFacturaProv = new javax.swing.JTextField();
        txtOrdemProv = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantUnidFact = new javax.swing.JTextField();
        txtPrecioFact = new javax.swing.JTextField();
        txtMontoFact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnRegistrarPagosSinOrdenCompras = new javax.swing.JButton();
        btnSalirRegistroFactura = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTributo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTotalImporte = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTemOrdenCompras = new javax.swing.JTextField();
        txtTem2 = new javax.swing.JTextField();
        EtqErrorFacturas = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        txtFechaSistema = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Registrar de Facturas ");

        txtCuitProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuitProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Proveedor  o Nro Orden");

        btnBuscarProveedor.setText("Buscar");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre de Proveedor");

        jLabel5.setText("Cuit");

        jLabel6.setText("Cuil");

        jLabel7.setText("Dirección");

        jLabel8.setText("Telefono");

        jLabel9.setText("Detalles...");

        JtablaRegistrarFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro. Fac", "OdenComp", "CodProd", "Fecha", "Descripción", "Cant/Unid", "Precio", "Monto"
            }
        ));
        jScrollPane1.setViewportView(JtablaRegistrarFactura);

        jLabel10.setText("Incluir en el Reglon");

        txtFacturaProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaProvActionPerformed(evt);
            }
        });

        txtOrdemProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdemProvActionPerformed(evt);
            }
        });

        txtPrecioFact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioFactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioFactKeyReleased(evt);
            }
        });

        txtMontoFact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFactFocusGained(evt);
            }
        });

        jLabel11.setText("Nro. Factura");

        jLabel12.setText("Ord. Comp");

        jLabel13.setText("Fecha");

        jLabel14.setText("Descripción del Productos");

        jLabel15.setText("Cant/Unid");

        jLabel16.setText("Precio");

        jLabel17.setText("Monto");

        btnRegistrarPagosSinOrdenCompras.setText("Incluir Reglon ");
        btnRegistrarPagosSinOrdenCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagosSinOrdenComprasActionPerformed(evt);
            }
        });

        btnSalirRegistroFactura.setText("Salir");
        btnSalirRegistroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegistroFacturaActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrar Factura");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        txtCodigoProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoProductoFocusGained(evt);
            }
        });
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyReleased(evt);
            }
        });

        jLabel18.setText("Cod. Prod");

        jLabel19.setText("Codigo");

        jLabel20.setText("Subtotal:");

        jLabel21.setText("Tributo:");

        jLabel22.setText("Total:");

        txtTemOrdenCompras.setEditable(false);
        txtTemOrdenCompras.setEnabled(false);
        txtTemOrdenCompras.setFocusable(false);
        txtTemOrdenCompras.setOpaque(false);
        txtTemOrdenCompras.setRequestFocusEnabled(false);

        txtTem2.setEditable(false);
        txtTem2.setEnabled(false);
        txtTem2.setFocusable(false);
        txtTem2.setOpaque(false);
        txtTem2.setRequestFocusEnabled(false);
        txtTem2.setSelectedTextColor(new java.awt.Color(240, 240, 240));

        EtqErrorFacturas.setText("jLabel23");

        jLabel23.setText("Numero de Factura-->");

        jLabel24.setText("Fecha de Recepcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSalirRegistroFactura)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFacturaProv, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtOrdemProv, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel15))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCantUnidFact, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPrecioFact, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16)))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EtqErrorFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtTributo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(btnRegistro)
                                            .addComponent(txtMontoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(129, 129, 129)
                                                .addComponent(btnRegistrarPagosSinOrdenCompras)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(467, 467, 467)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnBuscarProveedor))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel19))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(txtCuitProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCuilProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFechaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTFLProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTemOrdenCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtTem2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTemOrdenCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProveedor)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuitProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuilProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTFLProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(btnRegistrarPagosSinOrdenCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFacturaProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrdemProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantUnidFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EtqErrorFacturas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirRegistroFactura)
                    .addComponent(btnRegistro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuitProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuitProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitProveedorActionPerformed

    private void txtOrdemProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdemProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdemProvActionPerformed

    private void btnSalirRegistroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegistroFacturaActionPerformed
        
        //salir del modulo
        this.dispose();
    }//GEN-LAST:event_btnSalirRegistroFacturaActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        // Buscar Proveedor
        //BuscarProveedor();
        BuscarProveedorEnOrdenDeCompras();
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void txtPrecioFactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioFactKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             MultiplicarCantidadXPrecio();
         }
    }//GEN-LAST:event_txtPrecioFactKeyPressed

    private void txtPrecioFactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioFactKeyReleased
        // acción al presionar enter calcula la operación
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             MultiplicarCantidadXPrecio();
         }
    }//GEN-LAST:event_txtPrecioFactKeyReleased

    private void txtMontoFactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFactFocusGained
        // acción focus al perder el fucus calcula la operación
        MultiplicarCantidadXPrecio();
    }//GEN-LAST:event_txtMontoFactFocusGained

    private void btnRegistrarPagosSinOrdenComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagosSinOrdenComprasActionPerformed
        //Agragar Registro para el pago
        RegistrarPagosSinOrdenCompras();
        SumaRegistroFactura();
        LimpiarCajasTextoRegistroOrdenPagos();
        JOptionPane.showMessageDialog(this,"Registro Agregado a cuentas por pagar");
    }//GEN-LAST:event_btnRegistrarPagosSinOrdenComprasActionPerformed

    private void txtCodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyReleased
        // preciona enter para cargar descripción del producto
        BuscarProductoRegistroPorPagar();
    }//GEN-LAST:event_txtCodigoProductoKeyReleased

    private void txtCodigoProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoProductoFocusGained
        // cambia de caja de texto
        BuscarProductoRegistroPorPagar();
    }//GEN-LAST:event_txtCodigoProductoFocusGained

    private void txtFacturaProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaProvActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        int ordenComprasEnPagos=0;
        int idparapagos;
        int aux_temporal;
        aux_temporal=Integer.parseInt(OrdenComp);
        ordenComprasEnPagos=ConsultarOrdenDePagos();
        if(aux_temporal==ordenComprasEnPagos){
            JOptionPane.showMessageDialog(rootPane, "Orden fue pagada; consultar table de pagos");
        }else{
         Ordenparapago();   
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    // Metodos para consultar proveedor
    public void BuscarProveedor(){
        String sql_proveedor="SELECT * FROM proveedor WHERE id_proveedor=?";  
            try{
            PreparedStatement ps_proveedor=cn.prepareStatement(sql_proveedor);
            codproveedor=JOptionPane.showInputDialog(null, "Ingrese numero de proveedor");
            ResultSet rs;    
            ps_proveedor.setString(1,codproveedor);
            rs=ps_proveedor.executeQuery();
            while(rs.next()){
                txtCodProducto.setText(rs.getString("id_proveedor"));
                txtNombreProveedor.setText(rs.getString("nombre"));
                txtCuitProveedor.setText(rs.getString("cuit"));
                txtCuilProveedor.setText(rs.getString("cuil"));
                txtDireccionProveedor.setText(rs.getString("dir"));
                txtTFLProveedor.setText(rs.getString("tlf1"));
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No existe la orden de compra, "+ex);
        }
    }
    
    //Metodo para consultar Numero de Orden de Compras
    public void BuscarOrdenCompras(){
        String aux_Orden_compras=OrdenComp;
        String sql_OrdenCompras="SELECT * FROM comprageneral WHERE num_orden_id=?";  
            try{
            PreparedStatement ps_proveedor=cn.prepareStatement(sql_OrdenCompras);
            OrdenComp=JOptionPane.showInputDialog(null, "Ingrese numero de Orden de Compras");
            ResultSet rs;    
            ps_proveedor.setString(1,OrdenComp);
            rs=ps_proveedor.executeQuery();
            while(rs.next()){
                txtTemOrdenCompras.setText(rs.getString("num_orden_id"));
                txtTem2.setText(rs.getString("totalcompra"));
                aux_Orden_compras=(rs.getString("num_orden_id").toString());
                Aux_General_Proveedor=(rs.getString("proveedor_id").toString());
                sumaBDOrdenCompra=Double.parseDouble(rs.getString("totalcompra"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No existe la orden de compra, "+ex);
        }
        
    }
    
    // Buscar Cliente
    public void DatosRegistro(){
            String FactTemporal="00000";        
            String sql="SELECT idCompra, producto_id, fecha_compra, Descripcion_compra, cantida_compra, precio_compra, monto_compra FROM ordencompra WHERE idCompra=?";  
            try{
            PreparedStatement ps=cn.prepareStatement(sql);
            //CodigoOrden=JOptionPane.showInputDialog(null, "Ingrese numero de Orden de Compra");
         
            ResultSet rs;    
            ps.setString(1,OrdenComp);
            rs=ps.executeQuery();
            while(rs.next()){
                RegistroFactura[0]=String.valueOf(nrofactura); //"Numero de Factura"
                RegistroFactura[1]=rs.getString(1); //"Orden de Compras"
                RegistroFactura[2]=rs.getString(2); //"Codigo de Producto"
                RegistroFactura[3]=rs.getString(3); //"Fecha"
                RegistroFactura[4]=rs.getString(4); //"Descripción"
                RegistroFactura[5]=rs.getString(5); //"Cantidad o Unidad"
                RegistroFactura[6]=rs.getString(6); //"Precio"
                RegistroFactura[7]=rs.getString(7); //"Monto"                
                TablaFacturas.addRow(RegistroFactura); //"Agrega datos del Vector a la tabla de Manera Ordenada"
            }
            JtablaRegistrarFactura.setModel(TablaFacturas); //"se asigna datos a la tabla"
            
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No existe la orden de compra, "+ex);
        }
                
    }
    
    public void SumaRegistroFactura(){
        double suma1=0;
        double acumulaSuma=0;
        double ivafactura;
        for (int i = 0; i< JtablaRegistrarFactura.getRowCount(); i++) {
            suma1=Double.parseDouble( JtablaRegistrarFactura.getValueAt(i,7).toString());
            acumulaSuma=acumulaSuma+suma1;
        }
        if(suma1>0){
            txtSubTotal.setText(String.valueOf(acumulaSuma));
            ivafactura=acumulaSuma*0.21;
            txtTributo.setText(String.valueOf(ivafactura));
            txtTotalImporte.setText(String.valueOf(acumulaSuma+ivafactura));
            sumaRegistroFactura=(acumulaSuma+ivafactura);
        }
        
    }
    
public void BuscarProveedorXOrdenDeCompras(){    
    String sql_proveedor_compras="SELECT * FROM proveedor WHERE id_proveedor=?";  
            try{
            PreparedStatement ps_proveedor=cn.prepareStatement(sql_proveedor_compras);
            //codproveedor=JOptionPane.showInputDialog(null, "Ingrese numero de proveedor");
            ResultSet rs;    
            ps_proveedor.setString(1,Aux_General_Proveedor);
            rs=ps_proveedor.executeQuery();
            while(rs.next()){
                txtCodProducto.setText(rs.getString("id_proveedor"));
                txtNombreProveedor.setText(rs.getString("nombre"));
                txtCuitProveedor.setText(rs.getString("cuit"));
                txtCuilProveedor.setText(rs.getString("cuil"));
                txtDireccionProveedor.setText(rs.getString("dir"));
                txtTFLProveedor.setText(rs.getString("tlf1"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No existe la orden de compra, "+ex);
        }
            
    }

public void ErrorEnFactura(){
    int ordenComprasTemporalError;
    ordenComprasTemporalError=Integer.parseInt(OrdenComp);
    if(sumaRegistroFactura==sumaBDOrdenCompra || ordenComprasTemporalError!=ConsultarOrdenDePagos()){
        JOptionPane.showMessageDialog(null, "Verificandos Registros de Factura");
        EtqErrorFacturas.setText("Registros Verificados");
        EtqErrorFacturas.setForeground(Color.green);
//        EtqErrorFacturas.setForeground(font="serif".BOLD);
    }  
     else {
        JOptionPane.showMessageDialog(null,"Error Revisar Orden de Compras");
        EtqErrorFacturas.setText("Error");
        EtqErrorFacturas.setForeground(Color.red);
    }
    
}
// metodo para buscar proveedor en una orden de compras
private void BuscarProveedorEnOrdenDeCompras(){
    String sql_proveedor="SELECT * FROM proveedor WHERE id_proveedor=?";
    String opcion="";
    String nombre;
       int menu=0;
        opcion=JOptionPane.showInputDialog(null,"Ingrese una Opcion 1.Proveedor "+"2.Orden de Compras");
        menu=Integer.parseInt(opcion);
        
         switch(menu){
            case 1:
                //codproveedor=JOptionPane.showInputDialog(null,"Ingrese Codigo de Proveedor");
                  
                    try{
                    PreparedStatement ps_proveedor=cn.prepareStatement(sql_proveedor);
                    codproveedor=JOptionPane.showInputDialog(null, "Ingrese numero de proveedor");
                    nrofactura=JOptionPane.showInputDialog(null, "Ingrese numero de Factura");
                    ResultSet rs;    
                    ps_proveedor.setString(1,codproveedor);
                    rs=ps_proveedor.executeQuery();
                    while(rs.next()){
                    txtCodProducto.setText(rs.getString("id_proveedor"));
                    txtNombreProveedor.setText(rs.getString("nombre"));
                    txtCuitProveedor.setText(rs.getString("cuit"));
                    txtCuilProveedor.setText(rs.getString("cuil"));
                    txtDireccionProveedor.setText(rs.getString("dir"));
                    txtTFLProveedor.setText(rs.getString("tlf1"));
                    txtNumeroFactura.setText(nrofactura);
                    txtFacturaProv.setText(nrofactura);
                    txtOrdemProv.grabFocus();
                    txtFecha.setText(FechaActual());
                        }
                      }catch (SQLException ex) {
                        Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null,"No existe codigo del proveedor "+ex);
                    }
                break;
            case 2:
                      BuscarProveedorXOrdenDeCompras();
                      nrofactura=JOptionPane.showInputDialog(null, "Ingrese numero de Factura");
                      BuscarOrdenCompras();
                      DatosRegistro();
                      SumaRegistroFactura();
                      ErrorEnFactura();
                      BuscarProveedorXOrdenDeCompras();                      
                      txtNumeroFactura.setText(nrofactura);
                      txtFecha.setText(FechaActual());
                      txtFacturaProv.setText(nrofactura);
                      System.out.print("Oden de Pago Nro: "+ConsultarOrdenDePagos());
                break;            
                default:
               // opcion=JOptionPane.showInputDialog(null,"Salir del menu,  salir ingrese 3");
                JOptionPane.showMessageDialog(null,"hasta luego ");
                this.dispose();
                break;
                        
        }
}

// metodos para multiplicar cantidad x precion
public void MultiplicarCantidadXPrecio(){
    
            double factor1Cantidad, factor2Precio, monto=0; 
            factor2Precio=Double.parseDouble(txtPrecioFact.getText());
            factor1Cantidad=Double.parseDouble(txtCantUnidFact.getText());
             if(factor2Precio>0){ 
                 monto=(factor2Precio*factor1Cantidad);
                txtMontoFact.setText(Double.toString(monto));
             }else{
                 JOptionPane.showMessageDialog(null,"Precio debe ser mayor a cero");    
        }                                     
}
// metodos para registrar pagos manualmente directo sin orden de compras
public void RegistrarPagosSinOrdenCompras(){
    int cantidadOrden;
    double precioTem;
        String fechatem;
        cantidadOrden=Integer.parseInt(txtCantUnidFact.getText().toString());
        precioTem=Double.parseDouble(txtPrecioFact.getText());
        if(cantidadOrden>0 || precioTem>0 ){
                RegistroFactura[0]=String.valueOf(nrofactura).toString(); //"Numero de Factura"
                RegistroFactura[1]=txtOrdemProv.getText(); //"Orden de Compras"
                RegistroFactura[2]=txtCodigoProducto.getText(); //"Codigo de Producto"
                RegistroFactura[3]=txtFecha.getText(); //"Fecha"
                RegistroFactura[4]=txtDescripcion.getText(); //"Descripción"
                RegistroFactura[5]=txtCantUnidFact.getText(); //"Cantidad o Unidad"
                RegistroFactura[6]=String.valueOf(precioTem); //"Precio"
                RegistroFactura[7]=txtMontoFact.getText(); //"Monto"                
                TablaFacturas.addRow(RegistroFactura); //"Agrega datos del Vector a la tabla de Manera Ordenada"
            }
            JtablaRegistrarFactura.setModel(TablaFacturas); //"se asigna datos a la tabla"
}
public void LimpiarCajasTextoRegistroOrdenPagos(){
    // limpiar las cajas de texto
    txtFacturaProv.setText("");
    txtOrdemProv.setText("");
    txtCodigoProducto.setText("");
    txtFecha.setText("");
    txtDescripcion.setText("");
    txtCantUnidFact.setText("");
    txtPrecioFact.setText("");
    txtMontoFact.setText("");
}
public void BuscarProductoRegistroPorPagar(){
        double PrecioRegistro;
        String sqlBuscarProductoRegistros="SELECT descI,precioI FROM inventarios WHERE codigoI=?";  
            try{
            PreparedStatement ps_proveedor=cn.prepareStatement(sqlBuscarProductoRegistros);
            ResultSet rs;    
            ps_proveedor.setString(1,txtCodigoProducto.getText());
            rs=ps_proveedor.executeQuery();
            while(rs.next()){
                txtDescripcion.setText(rs.getString("descI"));
                PrecioRegistro=Double.parseDouble(rs.getString("precioI"));
                txtPrecioFact.setText(Double.toString(PrecioRegistro));
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Codigo de Producto no existe, Intente de nuevo");
        }
}
// fecha actual del sistema
public static String FechaActual(){
        Date Fecha =new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat("dd/MM/YYYY");
        
        return formatofecha.format(Fecha);
    }
 
// Metodo para Guardar en la tabla "ordenparaPagar"
private void Ordenparapago(){
    int codigo_proveedor, entero;
    int orden_compras = 0;
    String Cuit;
    Double monto, iva, total;
    String nro_factura;
    String fecha_registro;
    String fecha_recepción;
    String SQL_orden_para_pagar="INSERT INTO ordenparapagar(codigoProveedor,nrofactura,ordenCompras,cuit,subtotal,iva,totalpago,fechaDeRegistro,fechaRecepcion,ordenGenerada,ordenAprovada)value(?,?,?,?,?,?,?,?,?,?,?)";
    try {
        codigo_proveedor=Integer.parseInt(txtCodProducto.getText());
        nro_factura=txtNumeroFactura.getText();
        orden_compras=Integer.parseInt(OrdenComp);
        Cuit=txtCuitProveedor.getText();
        monto=Double.parseDouble(txtSubTotal.getText());
        iva=Double.parseDouble(txtTributo.getText());
        total=Double.parseDouble(txtTotalImporte.getText());
        fecha_registro=txtFechaSistema.getText();
        PreparedStatement OrdenPago=cn.prepareStatement(SQL_orden_para_pagar);
        
        OrdenPago.setInt(1,codigo_proveedor);
        OrdenPago.setString(2, nro_factura);
        OrdenPago.setInt(3, orden_compras);
        OrdenPago.setString(4, Cuit);
        OrdenPago.setDouble(5, monto);
        OrdenPago.setDouble(6, iva);
        OrdenPago.setDouble(7, total);
        OrdenPago.setString(8, fecha_registro);
        OrdenPago.setString(9, "");
        OrdenPago.setString(10, "1");
        OrdenPago.setString(11, "");
        entero=OrdenPago.executeUpdate();
        if(entero>0){
            JOptionPane.showMessageDialog(null,"Registro Generado");
        }
    } catch (SQLException ex) {
        Logger.getLogger(RegistrarFactura.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null,"Error en Registro de Orden de Pago ->"+ ex);
    }
    
}
//consultar orden para pago, si la orden de pago fue pagada
    public int ConsultarOrdenDePagos(){
        int ordenCompras=0;
        String Pagos="SELECT idOrdenParaPagar,ordenCompras FROM ordenparapagar WHERE ordenCompras=?";
         
    try {
        PreparedStatement ConsultaOrdenPago=cn.prepareStatement(Pagos);
        ResultSet rs;    
            ConsultaOrdenPago.setString(1,OrdenComp);
            rs=ConsultaOrdenPago.executeQuery();
            while(rs.next()){
                //idParaPagar=Integer.parseInt(rs.getNString("idOrdenParaPagar"));
                ordenCompras=Integer.parseInt(rs.getObject("ordenCompras").toString());
            }
     
    } catch (SQLException ex) {
        Logger.getLogger(RegistrarFactura.class.getName()).log(Level.SEVERE, null, ex);
    }
    return ordenCompras;
    }

    public static void main(String args[]) {
        /* Set the Nimbus loo and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtqErrorFacturas;
    private javax.swing.JTable JtablaRegistrarFactura;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnRegistrarPagosSinOrdenCompras;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalirRegistroFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantUnidFact;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtCuilProveedor;
    private javax.swing.JTextField txtCuitProveedor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtFacturaProv;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaSistema;
    private javax.swing.JTextField txtMontoFact;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtOrdemProv;
    private javax.swing.JTextField txtPrecioFact;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTFLProveedor;
    private javax.swing.JTextField txtTem2;
    private javax.swing.JTextField txtTemOrdenCompras;
    private javax.swing.JTextField txtTotalImporte;
    private javax.swing.JTextField txtTributo;
    // End of variables declaration//GEN-END:variables
}
